# Generated by Django 2.2.12 on 2020-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='typE',
        ),
        migrations.AddField(
            model_name='event',
            name='typE',
            field=models.CharField(blank=True, choices=[('i', 'Infosession'), ('a', 'infosession+Interview'), ('b', 'Interview Only')], default='i', help_text='Select a type for the event', max_length=1),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
