# Generated by Django 2.2.12 on 2020-06-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200611_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='join_zoom_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_zoom_url',
            field=models.CharField(max_length=1000),
        ),
    ]
