# Generated by Django 2.2.12 on 2020-06-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200611_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Event_type',
        ),
    ]
