# Generated by Django 2.2.12 on 2020-05-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='date_of_death',
        ),
    ]
