# Generated by Django 3.0.3 on 2020-06-03 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_Fair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career_Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('interview_duration', models.CharField(choices=[(4, 'Four minutes'), (5, 'Five minutes'), (6, 'Six minutes'), (7, 'Seven minutes'), (8, 'Eight minutes'), (9, 'Nine minutes'), (10, 'Ten minutes')], default=4, help_text='How long do you want every interaction to be? (per student)', max_length=1)),
                ('rest_duration', models.CharField(choices=[(1, 'One minutes'), (2, 'Two minutes'), (3, 'Three minutes'), (4, 'Four minutes')], default=2, help_text='How long do you need to rest between interactions?', max_length=1)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('university', models.CharField(max_length=100)),
                ('career_fair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career_fair.Career_Fair')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
