# Generated by Django 2.2.12 on 2020-06-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_fair', '0003_keyval_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_booth',
            name='booth_name',
            field=models.CharField(help_text='Optional. The name is only used on your calendar.', max_length=200),
        ),
    ]
