# Generated by Django 3.0.5 on 2020-06-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_fair', '0004_auto_20200616_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_booth',
            name='booth_name',
            field=models.CharField(max_length=200),
        ),
    ]
